---
all:
  children:
    build_hosts:
      hosts:
        build-host:
          ansible_host: build-node.internal.example.com
          ansible_user: ansible
          ansible_become: true

    deploy_targets:
      hosts:
        app-host-01:
          ansible_host: app-01.internal.example.com
          ansible_user: ansible
          ansible_become: true
        app-host-02:
          ansible_host: app-02.internal.example.com
          ansible_user: ansible
          ansible_become: true
